name: tremor_test_fe
description: "A new Flutter app for tremor testing"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5+1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Path & File handling
  path_provider: ^2.1.1
  path: ^1.8.3

  # JSON handling
  json_annotation: ^4.8.1

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9

  # Math & Complex numbers for FFT
  complex: ^0.8.0

  # CSV Export
  csv: ^6.0.0

  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/.

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
